version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - armhf
  - armv
  - automations
  - Buildx
  - chrisdrackett
  - cobertura
  - culori
  - datetime
  - falsey
  - fastify
  - hass
  - hassio
  - luxon
  - mstile
  - nderscore
  - nocomment
  - nums
  - Nuqs
  - shiki
  - shikijs
  - sonarjs
  - stefanzweifel
  - tseslint
  - typebox
  - vitesse
ignoreWords: []
import: []
